// Demo data — populates the dashboard without a login. Access via ?demo

const now = new Date()
const today = (h, m) => { const d = new Date(now); d.setHours(h, m, 0, 0); return d.toISOString() }
const hoursAgo = (h, mins = 0) => { const d = new Date(now); d.setHours(d.getHours() - h, d.getMinutes() - mins, 0, 0); return d.toISOString() }
const daysAgo = (days, h, m) => { const d = new Date(now); d.setDate(d.getDate() - days); d.setHours(h, m, 0, 0); return d.toISOString() }
const aptIn = (days, h, m) => {
  const d = new Date(now); d.setDate(d.getDate() + days)
  const hh = h > 12 ? `${h - 12}:${String(m).padStart(2, '0')}pm`
                    : h === 12 ? `12:${String(m).padStart(2, '0')}pm`
                    : `${h}:${String(m).padStart(2, '0')}am`
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')} at ${hh}`
}

export const DEMO_TRADE = {
  id: 'demo',
  business_name: 'Summit Roofing Ltd',
}

export const DEMO_ENQUIRIES = [
  {
    id: '1',
    customer_name: 'James Patterson',
    phone: '07411 234 567',
    email: 'james.p@gmail.com',
    postcode: 'SK4 2QP',
    town: 'Stockport',
    source: 'Website Widget',
    service_requested: 'Roof repair',
    urgency: 'Urgent / emergency',
    enquiry_intent: "I'd like someone to call me back",
    preferred_contact_time: 'Morning',
    status: 'Needs Action',
    action_tag: 'Call Back',
    created_at: hoursAgo(0, 12),
    custom_answers: [
      { question_text: 'Is the issue causing water to come into the property?', answer: 'Yes' },
      { question_text: 'What type of roof is it?', answer: 'Pitched roof' },
    ],
  },
  {
    id: '2',
    customer_name: 'Sarah Mitchell',
    phone: '07722 891 004',
    email: 'sarah.m@hotmail.co.uk',
    postcode: 'M20 1LP',
    town: 'Manchester',
    source: 'Website Widget',
    service_requested: 'Re-roofing',
    urgency: 'As soon as possible',
    enquiry_intent: "I'd like a quote",
    preferred_contact_time: 'Afternoon',
    status: 'Needs Action',
    action_tag: 'Quote Required',
    created_at: hoursAgo(1, 30),
    media_url: 'https://images.unsplash.com/photo-1632935175027-2c1f3f2e7eee?w=600&q=80',
    custom_answers: [
      { question_text: 'How old is the roof?', answer: 'Around 30 years' },
      { question_text: 'Any specific materials in mind?', answer: 'Slate, like original' },
    ],
  },
  {
    id: '3',
    customer_name: 'Mohammed Ali',
    phone: '07765 998 102',
    email: 'mali@outlook.com',
    postcode: 'M14 5RG',
    town: 'Fallowfield',
    source: 'Website Widget',
    service_requested: 'Emergency repair',
    urgency: 'Urgent / emergency',
    enquiry_intent: "I'd like to request a visit / survey",
    preferred_contact_time: 'Anytime',
    status: 'Needs Action',
    action_tag: 'Visit Required',
    created_at: hoursAgo(2, 45),
    custom_answers: [
      { question_text: 'Is the issue causing water to come into the property?', answer: 'Yes' },
      { question_text: 'How urgent is this?', answer: '3 tiles down, raining tonight' },
    ],
  },
  {
    id: '4',
    customer_name: 'Karen Williams',
    phone: '07900 123 456',
    email: 'karen.w@gmail.com',
    postcode: 'WA15 8JQ',
    town: 'Altrincham',
    source: 'Website Widget',
    service_requested: 'Flat roof',
    urgency: 'This week',
    enquiry_intent: "I'd like a quote",
    preferred_contact_time: 'Morning',
    status: 'In Process',
    action_tag: 'Quote Sent',
    created_at: daysAgo(4, 11, 20),
    internal_notes: '[02/06/25, 11:30] Called Karen - quote sent via email for £1,850. Awaiting response.',
  },
  {
    id: '5',
    customer_name: 'Lisa Thompson',
    phone: '07432 556 789',
    email: 'lisa.t@yahoo.co.uk',
    postcode: 'SK7 1NE',
    town: 'Bramhall',
    source: 'Website Widget',
    service_requested: 'Chimney work',
    urgency: 'Flexible / just looking',
    enquiry_intent: "I'd like to book directly if available",
    preferred_contact_time: 'Afternoon',
    booking_type: 'Site visit',
    status: 'Booked',
    action_tag: 'Visit Booked',
    appointment_datetime: aptIn(2, 14, 30),
    created_at: daysAgo(1, 11, 30),
    custom_answers: [
      { question_text: 'Type of chimney work?', answer: 'Repointing + new lead flashing' },
    ],
  },
  {
    id: '6',
    customer_name: 'Tom Bradley',
    phone: '07811 223 344',
    email: 'tom.bradley@gmail.com',
    postcode: 'M21 0BN',
    town: 'Chorlton',
    source: 'Website Widget',
    service_requested: 'Re-roofing',
    urgency: 'As soon as possible',
    enquiry_intent: "I'd like to book directly if available",
    booking_type: 'Quote',
    status: 'Booked',
    action_tag: 'Job Booked',
    appointment_datetime: aptIn(7, 9, 0),
    created_at: daysAgo(3, 10, 15),
    internal_notes: '[03/06/25, 14:20] Customer accepted £8,200 quote. Scheduled for next week.',
  },
  {
    id: '7',
    customer_name: 'Rachel Foster',
    phone: '07955 667 881',
    email: 'rachel.f@live.co.uk',
    postcode: 'SK3 8AB',
    town: 'Stockport',
    source: 'Website Widget',
    service_requested: 'Fascias & soffits',
    urgency: 'This week',
    enquiry_intent: "I'd like a quote",
    preferred_contact_time: 'Evening',
    status: 'In Process',
    action_tag: 'Waiting on Customer',
    created_at: daysAgo(3, 9, 0),
  },
  {
    id: '8',
    customer_name: 'David Chen',
    phone: '07855 443 210',
    email: 'd.chen@icloud.com',
    postcode: 'SK4 3NR',
    town: 'Heaton Moor',
    source: 'Website Widget',
    service_requested: 'Guttering',
    urgency: 'Flexible / just looking',
    enquiry_intent: "I'd like a quote",
    preferred_contact_time: 'Morning',
    status: 'In Process',
    action_tag: 'Contacted',
    created_at: daysAgo(2, 7, 30),
  },
  {
    id: '9',
    customer_name: 'Steve Marsh',
    phone: '07700 112 233',
    email: 'steve.marsh@btinternet.com',
    postcode: 'WA14 2QR',
    town: 'Altrincham',
    source: 'Website Widget',
    service_requested: 'Roof repair',
    urgency: 'This week',
    enquiry_intent: "I'd like to book directly if available",
    booking_type: 'Site visit',
    status: 'Booked',
    action_tag: 'Visit Booked',
    appointment_datetime: aptIn(1, 10, 0),
    created_at: daysAgo(4, 15, 45),
  },
  {
    id: '10',
    customer_name: 'Paul Naylor',
    phone: '07333 445 667',
    email: 'paul.n@yahoo.com',
    postcode: 'SK6 7DS',
    town: 'Marple',
    source: 'Website Widget',
    service_requested: 'Guttering',
    urgency: 'Flexible / just looking',
    enquiry_intent: "I'd like a quote",
    status: 'Booked',
    action_tag: 'Quote Accepted',
    created_at: daysAgo(6, 8, 50),
    internal_notes: '[Yesterday 16:05] Paul confirmed - cast iron Heritage style, deposit paid.',
  },
  {
    id: '11',
    customer_name: 'Diane Patel',
    phone: '07622 778 990',
    email: 'diane.p@gmail.com',
    postcode: 'M33 4TH',
    town: 'Sale',
    source: 'Website Widget',
    service_requested: 'Roof inspection',
    urgency: 'Urgent / emergency',
    enquiry_intent: "I'd like to request a visit / survey",
    preferred_contact_time: 'Anytime',
    status: 'Needs Action',
    action_tag: 'Visit Required',
    created_at: hoursAgo(4, 0),
  },
  {
    id: '12',
    customer_name: 'Emma Clarke',
    phone: '07488 334 556',
    email: 'emma.c@gmail.com',
    postcode: 'M19 2FH',
    town: 'Levenshulme',
    source: 'Website Widget',
    service_requested: 'Flat roof',
    urgency: 'As soon as possible',
    enquiry_intent: "I'd like a quote",
    preferred_contact_time: 'Morning',
    status: 'In Process',
    action_tag: 'Appointment Agreed',
    created_at: daysAgo(5, 13, 20),
  },
]

export const DEMO_STATS = {
  total_enquiries: 12,
  needs_action_count: 4,
  in_process_count: 4,
  booked_count: 4,
}
